<?php return array (
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'October\\Demo\\Components\\Todo' => 'plugins/october/demo/components/Todo.php',
  'backend\\Controllers\\index' => 'modules/backend/controllers/index.php',
  'backend\\Controllers\\auth' => 'modules/backend/controllers/auth.php',
  'cms\\Controllers\\index' => 'modules/cms/controllers/index.php',
  'backend\\Controllers\\media' => 'modules/backend/controllers/media.php',
  'system\\Controllers\\settings' => 'modules/system/controllers/settings.php',
  'cms\\Controllers\\themes' => 'modules/cms/controllers/themes.php',
  'system\\Controllers\\updates' => 'modules/system/controllers/updates.php',
  'rainlab\\blog\\Plugin' => 'plugins/rainlab/blog/Plugin.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins/rainlab/blog/models/Post.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins/rainlab/blog/classes/TagProcessor.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins/rainlab/blog/models/Category.php',
  'backend\\Controllers\\users' => 'modules/backend/controllers/users.php',
  'system\\Controllers\\mailtemplates' => 'modules/system/controllers/mailtemplates.php',
  'system\\Controllers\\eventlogs' => 'modules/system/controllers/eventlogs.php',
);